# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.8
_src_path: ../../ModernAppTemplate/frontend
author_email: dev@example.com
author_name: Developer
backend_port: 3201
frontend_port: 3200
image_name: registry:5000/iot-support
project_description: IoT device management and support platform
project_name: iot-support
project_title: IoT Support
repo_url: ''
sse_gateway_port: 3001
use_app_shell: true
use_oidc: true
use_sse: true
